/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppPage: typeof import('./src/components/app-page/app-page.vue')['default']
    AppTabbar: typeof import('./src/components/app-tabbar/app-tabbar.vue')['default']
    UAvatar: typeof import('uview-pro/components/u-avatar/u-avatar.vue')['default']
    UBadge: typeof import('uview-pro/components/u-badge/u-badge.vue')['default']
    UButton: typeof import('uview-pro/components/u-button/u-button.vue')['default']
    UCard: typeof import('uview-pro/components/u-card/u-card.vue')['default']
    UCellGroup: typeof import('uview-pro/components/u-cell-group/u-cell-group.vue')['default']
    UCellItem: typeof import('uview-pro/components/u-cell-item/u-cell-item.vue')['default']
    UConfigProvider: typeof import('uview-pro/components/u-config-provider/u-config-provider.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    UImage: typeof import('uview-pro/components/u-image/u-image.vue')['default']
    ULink: typeof import('uview-pro/components/u-link/u-link.vue')['default']
    ULoading: typeof import('uview-pro/components/u-loading/u-loading.vue')['default']
    UMask: typeof import('uview-pro/components/u-mask/u-mask.vue')['default']
    UNavbar: typeof import('uview-pro/components/u-navbar/u-navbar.vue')['default']
    UTabbar: typeof import('uview-pro/components/u-tabbar/u-tabbar.vue')['default']
    UText: typeof import('uview-pro/components/u-text/u-text.vue')['default']
    UToast: typeof import('uview-pro/components/u-toast/u-toast.vue')['default']
    UTransition: typeof import('uview-pro/components/u-transition/u-transition.vue')['default']
  }
}
